=begin
#ESP Documentation

#The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

OpenAPI spec version: v2_sdk

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::APIKeysApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'APIKeysApi' do
  before do
    # run before each test
    @instance = ESP::APIKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of APIKeysApi' do
    it 'should create an instact of APIKeysApi' do
      expect(@instance).to be_instance_of(ESP::APIKeysApi)
    end
  end

  # unit tests for create
  # Create a(n) API Key
  # The secret key will only be returned once when the key is first created
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The name of the API Key
  # @option opts [String] :include Related objects that can be included in the response:  user See Including Objects for more information.
  # @return [APIKey]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a(n) API Key
  # 
  # @param id  ID
  # @param [Hash] opts the optional parameters
  # @return [Meta]
  describe 'delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Get a list of API Keys
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page Page Number and Page Size.  number is the page number of the collection to return, size is the number of items to return per page
  # @option opts [String] :include Related objects that can be included in the response:  user See Including Objects for more information.
  # @return [PaginatedCollection]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single API Key
  # 
  # @param id API Key ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Related objects that can be included in the response:  user See Including Objects for more information.
  # @return [APIKey]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Update a(n) API Key
  # 
  # @param id API Key ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The name of the API Key
  # @option opts [String] :include Related objects that can be included in the response:  user See Including Objects for more information.
  # @return [APIKey]
  describe 'update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
