=begin
#ESP Documentation

#The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

OpenAPI spec version: v2_sdk

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::AuditLogFileExportApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuditLogFileExportApi' do
  before do
    # run before each test
    @instance = ESP::AuditLogFileExportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditLogFileExportApi' do
    it 'should create an instact of AuditLogFileExportApi' do
      expect(@instance).to be_instance_of(ESP::AuditLogFileExportApi)
    end
  end

  # unit tests for create
  # Export an Audit Log File
  # 
  # @param [Hash] opts the optional parameters
  # @return [AuditLogFile]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single Audit Log File
  # 
  # @param id Audit Log File Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Objects that can be included in the response:  organization,user  See Including Objects for more information.
  # @return [AuditLogFile]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
