=begin
#ESP Documentation

#The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

OpenAPI spec version: v2_sdk

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::CustomComplianceStandardsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomComplianceStandardsApi' do
  before do
    # run before each test
    @instance = ESP::CustomComplianceStandardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomComplianceStandardsApi' do
    it 'should create an instact of CustomComplianceStandardsApi' do
      expect(@instance).to be_instance_of(ESP::CustomComplianceStandardsApi)
    end
  end

  # unit tests for create
  # Create a(n) Custom Compliance Standard
  # 
  # @param description The description for this Compliance Standard
  # @param name Name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Related objects that can be included in the response:  custom_compliance_domains, custom_compliance_controls See Including Objects for more information.
  # @return [CustomComplianceStandard]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a(n) Custom Compliance Standard
  # 
  # @param id Custom Compliance Standard ID
  # @param [Hash] opts the optional parameters
  # @return [Meta]
  describe 'delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single Custom Compliance Standard
  # 
  # @param id Custom Compliance Standard ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Related objects that can be included in the response:  custom_compliance_domains, custom_compliance_controls See Including Objects for more information.
  # @return [CustomComplianceStandard]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Update a(n) Custom Compliance Standard
  # 
  # @param id Custom Compliance Standard ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Related objects that can be included in the response:  custom_compliance_domains, custom_compliance_controls See Including Objects for more information.
  # @option opts [String] :description The description for this Compliance Standard
  # @option opts [String] :name Name
  # @return [CustomComplianceStandard]
  describe 'update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
