=begin
#ESP Documentation

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::DashboardApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DashboardApi' do
  before do
    # run before each test
    @instance = ESP::DashboardApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DashboardApi' do
    it 'should create an instact of DashboardApi' do
      expect(@instance).to be_instance_of(ESP::DashboardApi)
    end
  end

  # unit tests for recent
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, String>] :page Page Number
  # @return [PaginatedCollection]
  describe 'recent test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
