=begin
#ESP Documentation

#The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

OpenAPI spec version: v2_sdk

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::MetadataApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MetadataApi' do
  before do
    # run before each test
    @instance = ESP::MetadataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MetadataApi' do
    it 'should create an instact of MetadataApi' do
      expect(@instance).to be_instance_of(ESP::MetadataApi)
    end
  end

  # unit tests for for_alert
  # Show the metadata for an alert
  # 
  # @param alert_id Alert Id
  # @param [Hash] opts the optional parameters
  # @return [Metadata]
  describe 'for_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single Metadata
  # 
  # @param id Metadata Id
  # @param [Hash] opts the optional parameters
  # @return [Metadata]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
