=begin
#ESP Documentation

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::RegionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RegionsApi' do
  before do
    # run before each test
    @instance = ESP::RegionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RegionsApi' do
    it 'should create an instact of RegionsApi' do
      expect(@instance).to be_instance_of(ESP::RegionsApi)
    end
  end

  # unit tests for list
  # Get a list of Regions
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, String>] :page Page Number
  # @option opts [Hash<String, String>] :filter Filter Params for Searching
  # @return [PaginatedCollection]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single Region
  # 
  # @param id Region Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Included Objects
  # @return [Region]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
