=begin
#ESP Documentation

#The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

OpenAPI spec version: v2_sdk

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::ReportIntegrationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReportIntegrationsApi' do
  before do
    # run before each test
    @instance = ESP::ReportIntegrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportIntegrationsApi' do
    it 'should create an instact of ReportIntegrationsApi' do
      expect(@instance).to be_instance_of(ESP::ReportIntegrationsApi)
    end
  end

  # unit tests for create
  # Export all alerts on reports to an integration
  # 
  # @param report_ids An array of report IDs
  # @param integration_id The ID of the integration to send the alerts to
  # @param [Hash] opts the optional parameters
  # @return [SuccessObject]
  describe 'create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
