=begin
#ESP Documentation

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::SignaturesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SignaturesApi' do
  before do
    # run before each test
    @instance = ESP::SignaturesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SignaturesApi' do
    it 'should create an instact of SignaturesApi' do
      expect(@instance).to be_instance_of(ESP::SignaturesApi)
    end
  end

  # unit tests for list
  # Get a list of Signatures
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, String>] :page Page Number
  # @option opts [Hash<String, String>] :filter Filter Params for Searching
  # @option opts [String] :include Included Objects
  # @return [PaginatedCollection]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for run
  # A successful call to this API returns a list of alerts for the specific signature identified by the id parameter. The body of the request must contain a json api compliant hash of attributes with type signatures
  # 
  # @param id The ID of the signature to run
  # @param external_account_id The ID of the external account to run this signature against
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :region A single region name to run this signature against
  # @return [Array<Alert>]
  describe 'run test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single Signature
  # 
  # @param id Signature Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Included Objects
  # @return [Signature]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
