=begin
#ESP Documentation

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ESP::SuppressionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SuppressionsApi' do
  before do
    # run before each test
    @instance = ESP::SuppressionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SuppressionsApi' do
    it 'should create an instact of SuppressionsApi' do
      expect(@instance).to be_instance_of(ESP::SuppressionsApi)
    end
  end

  # unit tests for deactivate
  # A successful call to this API will deactivate a suppression identified by the id parameter.
  # 
  # @param id Suppression Id
  # @param [Hash] opts the optional parameters
  # @return [Suppression]
  describe 'deactivate test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Get a list of Suppressions
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, String>] :page Page Number
  # @option opts [Hash<String, String>] :filter Filter Params for Searching
  # @option opts [String] :include Included Objects
  # @return [PaginatedCollection]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show
  # Show a single Suppression
  # 
  # @param id Suppression Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Included Objects
  # @return [Suppression]
  describe 'show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
